---
title: "Environmental Social Governance"
author: "Tyler Wilson"
date: "7/25/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(janitor) 
library(GGally)
library(lubridate)
library(viridis)
```

```{r data_import}
esg_country <- read_csv(here('data/ESGCountry.csv'))
esg_data <- read_csv(here('data/ESGData.csv'))
esg_series <- read_csv(here('data/ESGSeries.csv'))
esg_time_series <- read_csv(here('data/ESGSeries-Time.csv'))
esg_country_series <- read_csv(here('data/ESGCountry-Series.csv'))
# also have foot_note data
```

```{r}
esg_country$X31 <- NULL
esg_data$X66 <- NULL
esg_country_series$X4 <- NULL
esg_series$X21 <- NULL
esg_time_series$X4 <- NULL
```

```{r}
esg_country <- esg_country %>% clean_names()
esg_data <- esg_data %>% clean_names()
esg_country_series <- esg_country_series %>% clean_names()
esg_series <- esg_series %>% clean_names()
esg_time_series <- esg_time_series %>% clean_names()
```


```{r}
country <- esg_country %>% 
  select(country_code, region, income_group, national_accounts_base_year, national_accounts_reference_year, sna_price_valuation, lending_category, system_of_national_accounts, ppp_survey_year, balance_of_payments_manual_in_use, external_debt_reporting_status, system_of_trade, government_accounting_concept, imf_data_dissemination_standard, latest_population_census, latest_household_survey, vital_registration_complete, latest_agricultural_census, latest_industrial_data, latest_trade_data) %>% 
  mutate_if(is.character, as_factor) %>% 
  mutate_if(is.logical, as_factor)
```

```{r}
esg <- esg_data %>% 
  select(-country_name, -indicator_code)
```

```{r}
esg %>% 
  pivot_longer(c(-country_code, -indicator_name), names_to = 'year', names_prefix = 'x') %>% 
  mutate(year = year(make_date(year))) %>% 
  count(indicator_name)

esg %>% 
  pivot_longer(c(-country_code, - indicator_name), names_to = 'year', names_prefix = 'x') %>% 
  mutate(year = year(make_date(year))) %>% 
  na.omit() %>% 
  filter(indicator_name == 'Access to clean fuels and technologies for cooking (% of population)') %>% 
  ggplot(aes(year, value)) +
  geom_line(aes(group = country_code, color = country_code)) +
  scale_color_viridis(discrete = T) +
  # facet_wrap(~ indicator_name, scales = 'free') +
  theme(legend.position = 'none')

esg <- esg %>% 
  pivot_longer(c(-country_code, - indicator_name), names_to = 'year', names_prefix = 'x') %>% 
  mutate(year = year(make_date(year))) %>% 
  na.omit()
```

```{r}
esg2 <- esg %>% 
  pivot_wider(id_cols = c(country_code, year), names_from = indicator_name) %>% 
  clean_names() %>% 
  discard(~all(is.na(.)))
  
esg_scaled <- esg2 %>% 
  select(-year) %>% 
  mutate_if(is.numeric, scale) %>% 
  mutate(year = esg2$year) %>% 
  pivot_longer(c(-country_code, -year), names_to = 'indicator') %>% 
  mutate(value = value[,1])

countries_investigate <- esg_scaled %>% 
  na.omit() %>% 
  filter(year == max(year)) %>% 
  group_by(indicator, country_code) %>% 
  summarise(avg = mean(value)) %>% 
  slice_max(avg, n = 1) %>% 
  ungroup() %>% 
  select(country_code) %>% 
  unique() %>% 
  as.list() %>% 
  unname() %>% 
  unlist()
  

esg_scaled %>% 
  filter(country_code == countries_investigate) %>% 
  na.omit() %>% 
  ggplot(aes(year, value)) +
  geom_line(aes(group = country_code, color = country_code)) +
  theme(legend.position = 'none') +
  facet_wrap(~ indicator, scales = 'free')


esg_scaled %>% 
  pivot_wider(id_cols = c(country_code, year), names_from = indicator)

country


```

